src/Entity/RecipeFabrication.php
<?php

namespace App\Entity;

use App\Interfaces\IRecipe;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecipeFabricationRepository")
 */
class RecipeFabrication implements IRecipe
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Recipe", inversedBy="recipeFabrications")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipe;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=5)
     */
    private $marge;

    /**
     * @ORM\Column(type="decimal",precision=10,scale=4)
     */
    private $quantity;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Taxe", inversedBy="recipeFabrications")
     */
    private $taxes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RecipeFabricationComponent", mappedBy="recipeFabrication",cascade={"persist"})
     */
    private $recipeFabricationComponents;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $hours=0;

    /**
     * @ORM\Column(type="boolean")
     */
    private $ended = false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $finalised = false;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Unit", inversedBy="recipeFabrications")
     * @ORM\JoinColumn(nullable=false)
     */
    private $unit;

    public function __construct()
    {
        $this->taxes = new ArrayCollection();
        $this->recipeFabricationComponents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRecipe(): ?Recipe
    {
        return $this->recipe;
    }

    public function setRecipe(?Recipe $recipe): self
    {
        $this->recipe = $recipe;

        return $this;
    }

    public function getMarge(): ?string
    {
        return $this->marge;
    }

    public function setMarge(string $marge): self
    {
        $this->marge = $marge;

        return $this;
    }

    public function getQuantity(): ?float
    {
        return $this->quantity;
    }

    public function setQuantity(float $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * @return Collection|Taxe[]
     */
    public function getTaxes(): Collection
    {
        return $this->taxes;
    }

    public function addTax(Taxe $tax): self
    {
        if (!$this->taxes->contains($tax)) {
            $this->taxes[] = $tax;
        }

        return $this;
    }

    public function removeTax(Taxe $tax): self
    {
        if ($this->taxes->contains($tax)) {
            $this->taxes->removeElement($tax);
        }

        return $this;
    }
    /**
     * @return Collection|RecipeFabricationComponent[]
     */
    public function getRecipeFabricationComponents(): Collection
    {
        return $this->recipeFabricationComponents;
    }

    public function addRecipeFabricationComponents(RecipeFabricationComponent $recipeFabricationComponent): self
    {
        if (!$this->recipeFabricationComponents->contains($recipeFabricationComponent)) {
            $this->recipeFabricationComponents[] = $recipeFabricationComponent;
        }

        return $this;
    }

    public function removeRecipeFabricationComponent(RecipeFabricationComponent $recipeFabricationComponent): self
    {
        if ($this->recipeFabricationComponents->contains($recipeFabricationComponent)) {
            $this->recipeFabricationComponents->removeElement($recipeFabricationComponent);
        }

        return $this;
    }
    public function getHours(): ?string
    {
        return $this->hours;
    }

    public function setHours(string $hours): self
    {
        $this->hours = $hours;

        return $this;
    }

    public function getEnded(): bool
    {
        return $this->ended;
    }

    public function setEnded(bool $ended = null): self
    {
        $ended = $ended === null ? false: $ended;
        $this->ended = $ended;

        return $this;
    }

    public function getCalculatedHours()
    {
        $diff = (new \DateTime())->diff($this->getCreatedAt());
        $hours = round($diff->s / 3600 + $diff->i / 60 + $diff->h + $diff->days * 24, 2);
        return $hours;
    }
    /**
     * @return Collection|RecipeComponent[]
     */
    public function getTheRecipeComponents(): Collection
    {
        return $this->getRecipeFabricationComponents();
    }

    public function getFinalised(): ?bool
    {
        return $this->finalised;
    }

    public function setFinalised(?bool $finalised): self
    {
        $this->finalised = $finalised;

        return $this;
    }

    public function getAmount()
    {
        $amount = 0;
        foreach($this->getRecipeFabricationComponents() AS $component){
            $amount += $component->getAmount();
        }
        return $amount;
    }

    public function getUnit(): ?Unit
    {
        return $this->unit;
    }

    public function setUnit(?Unit $unit): self
    {
        $this->unit = $unit;

        return $this;
    }
}

src/Controller/RecipeFabricationController.php
<?php

namespace App\Controller;

use App\Entity\Component;
use App\Entity\Inventory;
use App\Entity\Price;
use App\Entity\Recipe;
use App\Entity\RecipeFabrication;
use App\Entity\RecipeFabricationComponent;
use App\Form\RecipeFabricationType;
use App\Form\RecipeType;
use App\Repository\ComponentRepository;
use App\Repository\InventoryRepository;
use App\Repository\RecipeFabricationRepository;
use App\Repository\RecipeRepository;
use App\Repository\TaxeRepository;
use App\Service\ImageService;
use App\Service\InventoryService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\VarDumper\VarDumper;

/**
 * @Route("/fabrication")
 */
class RecipeFabricationController extends AbstractController
{
    /**
     * @Route("/", name="fabrication_index", methods={"GET"})
     * @param RecipeFabricationRepository $recipeFabricationRepository
     * @return Response
     */
    public function index(RecipeFabricationRepository $recipeFabricationRepository): Response
    {
        return $this->render('front/recipe_fabrication/index.html.twig', [
            'recipes' => $recipeFabricationRepository->createQueryBuilder('r')
                ->leftJoin('r.recipe', 'recipe')
                ->where('recipe.user = :user')
                ->andWhere('r.finalised = false')
                ->setParameter('user', $this->getUser())
                ->orderBy('r.createdAt', 'DESC')
                ->getQuery()->getResult()
        ]);
    }


    /**
     * @Route("/sell/{id}", name="fabrication_sell", methods={"GET"})
     * @param RecipeFabricationRepository $recipeFabricationRepository
     * @return Response
     */
    public function sell(RecipeFabricationRepository $recipeFabricationRepository): Response
    {
        return $this->render('front/recipe_fabrication/index.html.twig', [
            'recipes' => $recipeFabricationRepository->createQueryBuilder('r')
                ->leftJoin('r.recipe', 'recipe')
                ->where('recipe.user = :user')
                ->setParameter('user', $this->getUser())
                ->orderBy('r.createdAt', 'DESC')
                ->getQuery()->getResult()
        ]);
    }

    /**
     * @Route("/inventoring/{id}", name="fabrication_inventoring", methods={"GET"})
     * @param RecipeFabricationRepository $recipeFabricationRepository
     * @return Response
     */
    public function inventoring(RecipeFabrication $recipeFabrication, InventoryRepository $inventoryRepository, ComponentRepository $componentRepository): Response
    {
        $inventory = new Inventory();
        $productLabel = ucfirst(strtolower($recipeFabrication->getRecipe()->getLabel()));
        try {
            $component = $componentRepository->findOneBy(['label' => $productLabel, 'user' => $this->getUser()]);
            $em = $this->getDoctrine()->getManager();
            $quantity = $recipeFabrication->getQuantity() * $recipeFabrication->getRecipe()->getProportion();
            $inventory->setQuantity($quantity);
            $inventory->setUnit($recipeFabrication->getUnit());
            $inventory->setPrice($recipeFabrication->getAmount());
            if ($component == null) {
                $component = new Component();
                $component->setLabel($productLabel);
                $component->setUser($this->getUser());
                $em->persist($component);
            }

            $tmpInventory = $inventoryRepository->findOneBy(['user' => $this->getUser(), 'price' => $inventory->getPrice(), 'optionLabel' => $inventory->getOptionLabel(), 'component' => $component]);
            if ($tmpInventory != null) {
                $tmpInventory->setQuantity($inventory->getQuantity() + $tmpInventory->getQuantity());
                $inventory = $tmpInventory;
            } else {
                $inventory->setComponent($component);
                $inventory->setUser($this->getUser());
                $em->persist($inventory);
            }

            $component->addInventory($inventory);
            $component->setCommunityEnabled(false);
            if (!$component->hasPrices($inventory->getPrice())) {
                $price = new Price();
                $price->setUnitPrice($inventory->getPrice());
                $price->setTaxToApply(0);
                $price->setAutoUpdateEnabled(false);
                $component->addPrice($price);
                $em->persist($price);
            }
            $recipeFabrication->setFinalised(true);
            $em->flush();
            $this->addFlash('success', 'flashes.message.success.added_inventory');
        } catch (Exception $e) {
            $this->addFlash('danger', 'flashes.message.danger.added_inventory');
        }

        return $this->redirectToRoute('fabrication_index');
    }

    /**
     * @Route("/{id}/fabrique", name="recipe_fabricate", methods={"GET","POST"})
     * @param Request $request
     * @param Recipe $recipe
     * @param InventoryService $inventoryService
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function start(Request $request, Recipe $recipe, InventoryService $inventoryService, EntityManagerInterface $entityManager): Response
    {
        if ($this->getUser() != $recipe->getUser()) {
            $this->addFlash('danger', 'text.danger.not_yours');
            return $this->redirectToRoute('taxe_index');
        }
        $recipeFabrication = new RecipeFabrication();
        $recipeFabrication->setRecipe($recipe);
        $recipeFabrication->setUnit($recipe->getUnit());
        foreach ($recipe->getTaxes() AS $taxe) {
            $recipeFabrication->addTax($taxe);
        }
        $options = $request->get('options', []);
        $prices = $request->get('prices', []);

        foreach ($recipe->getRecipeComponents() AS $component) {
            $recipeCompo = new RecipeFabricationComponent();
            $recipeCompo->setQuantity($component->getQuantity());
            $recipeCompo->setComponent($component->getComponent());
            if (isset($options[$component->getId()])) {
                $recipeCompo->setOptionLabel($options[$component->getId()]);
            }
            if (isset($prices[$component->getId()])) {
                $recipeCompo->setAmount($prices[$component->getId()]);
            }

            $recipeCompo->setDescription($component->getDescription());
            $recipeCompo->setUnit($component->getUnit());
            $recipeCompo->setRecipeFabrication($recipeFabrication);
            $recipeFabrication->addRecipeFabricationComponents($recipeCompo);
        }
        $recipeFabrication->setMarge($recipe->getMarge());
        $recipeFabrication->setQuantity(1);

        $form = $this->createForm(RecipeFabricationType::class, $recipeFabrication);

        $form->handleRequest($request);
        if($request->get('estimate', null)){
            $recipeFabrication->setHours($recipe->getEstimatedHours());
            return $this->estimate($recipeFabrication);
        }
        if ($form->isSubmitted() && $form->isValid()) {
            if ($recipeFabrication->getEnded() == true) {
                foreach ($recipeFabrication->getRecipeFabricationComponents() AS $component) {
                    $inventoryService->sub($component, floatval($recipeFabrication->getQuantity()) * floatval($component->getQuantity()));
                }
            }

            $entityManager->persist($recipeFabrication);
            $entityManager->flush();

            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('front/recipe_fabrication/start.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
            'fabrication' => $recipeFabrication,
        ]);
    }

    /**
     * @Route("/{id}/estimate", name="recipe_estimate", methods={"GET","POST"})
     * @param RecipeFabrication $recipeFabrication
     * @return Response
     */
    public function estimate(RecipeFabrication $recipeFabrication): Response
    {
        return $this->render('front/recipe_fabrication/estimate.html.twig', [
            'recipe' => $recipeFabrication
        ]);
    }

    /**
     * @Route("/{id}/fabrique/continue", name="recipe_continue_fabricate", methods={"GET","POST"})
     * @param Request $request
     * @param RecipeFabrication $recipeFabrication
     * @param InventoryService $inventoryService
     * @return Response
     */
    public function continue(Request $request, RecipeFabrication $recipeFabrication, InventoryService $inventoryService): Response
    {
        if ($this->getUser() != $recipeFabrication->getRecipe()->getUser()) {
            $this->addFlash('danger', 'text.danger.not_yours');
            return $this->redirectToRoute('taxe_index');
        }
        $form = $this->createForm(RecipeFabricationType::class, $recipeFabrication);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if ($recipeFabrication->getEnded() == true) {
                foreach ($recipeFabrication->getRecipeFabricationComponents() AS $component) {
                    $inventoryService->sub($component, floatval($recipeFabrication->getQuantity()) * floatval($component->getQuantity()));
                }
            }

            $options = $request->get('options', []);
            $prices = $request->get('prices', []);
            foreach ($recipeFabrication->getRecipeFabricationComponents() AS $component) {
                if (isset($options[$component->getId()])) {

templates/front/recipe_fabrication/_delete_form.html.twig
<form class='delete-button-form' method="post" action="{{ path('recipe_delete', {'id': recipe.id}) }}" onsubmit="return confirm({{ "text.confirm_delete"|trans}});">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn btn-danger btn-block btn-square "><i class="fas fa-trash"></i></button>
</form>

templates/front/recipe_fabrication/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.recipe.edit"|trans }} {{ parent() }}{% endblock %}

{% block contentHeader %}
    {% include 'tools/content_header.html.twig' with {title: "title.recipe.edit"|trans } %}

{% endblock %}
{% block content %}

            {{ include('front/recipe/_form.html.twig', {'button_label': 'button.default.edit'|trans, title:"title.recipe.edit"|trans }) }}

{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('form_recipe') }}
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('form_recipe') }}
{% endblock %}

templates/front/recipe_fabrication/estimate.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.recipe.start_recipe"|trans }} {{ parent() }}{% endblock %}

{% block contentHeader %}
    {% include 'tools/content_header.html.twig' with {title: "title.recipe.start_recipe"|trans } %}

{% endblock %}
{% block content %}
    <div class="row">
      {% include '/front/recipe_fabrication/partial/addition.html.twig' with  {recipe:recipe } %}

    </div>
{% endblock %}

{% block javascripts %}
{% endblock %}

{% block stylesheets %}
{% endblock %}

templates/front/recipe_fabrication/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.recipe.new"|trans }} {{ parent() }}{% endblock %}
{% block contentHeader %}
    {% include 'tools/content_header.html.twig' with {title: "title.recipe.new"|trans } %}
{% endblock %}

{% block content %}
    {{ include('front/recipe/_form.html.twig',{title:"title.recipe.new"|trans }) }}
{% endblock %}
{% block javascripts %}
{{ encore_entry_script_tags('form_recipe') }}
{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('form_recipe') }}
{% endblock %}

templates/front/recipe_fabrication/start.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.recipe.start_recipe"|trans }} {{ parent() }}{% endblock %}

{% block contentHeader %}
    {% include 'tools/content_header.html.twig' with {title: "title.recipe.start_recipe"|trans } %}

{% endblock %}
{% block content %}
    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "title.recipe.start_recipe %recipe%"|trans({'%recipe%':recipe.label}) }}</h3>
                </div>
                <div class="card-body p-3">
                    <div data-intro="{{ "intro.text.recipe.marge"|trans }}">
                        {{ form_row(form.quantity) }}
                    </div>
                    <div data-intro="{{ "intro.text.recipe.marge"|trans }}">
                        {{ form_row(form.marge) }}
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "entity.recipe.label.recipeComponents"|trans }}</h3>
                </div>
                <div class="card-body p-0" data-intro="{{ "intro.text.recipe.components"|trans }}">
                    <table id="components-fields-list" class="table table-condensed">

                        <thead>
                        <tr>
                            <th>{{ "entity.recipe_component.label.component"|trans }}</th>
                            <th>{{ "entity.recipe_component.label.option"|trans }}</th>
                            <th>{{ "entity.recipe_component.label.quantity"|trans }}</th>
                            <th></th>
                            <th>{{ "entity.recipe_component.label.cost"|trans }}</th>
                        </tr>
                        </thead>
                        {% if fabrication.id is null %}
                            {% for component in recipe.recipeComponents %}
                                <tr>
                                    <td>{{ component.component.label }}</td>
                                    <td data-type="new" data-component="{{ component.id }}"></td>
                                    <td>{{ component.quantity }} {{ component.unit.libelle }}</td>
                                    <td class="enougth"><i class="fas fa-question text-warning"></i></td>
                                    <td class="price"></td>
                                </tr>
                                <tr><td colspan="5">{{ component.description }}</td></tr>
                            {% endfor %}
                        {% else %}
                            {% for component in fabrication.recipeFabricationComponents %}
                                <tr>
                                    <td>{{ component.component.label }}</td>
                                    <td data-type="edit" data-component="{{ component.id }}"></td>
                                    <td>{{ component.quantity }} {{ component.unit.libelle }}</td>
                                    <td class="enougth"><i class="fas fa-question text-warning"></i></td>
                                    <td class="price"></td>
                                </tr>
                                <tr><td colspan="5">{{ component.description }}</td></tr>

                            {% endfor %}
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "entity.recipe.label.taxes"|trans }}</h3>
                </div>
                <div class="card-body p-3" data-intro="{{ "intro.text.recipe.taxes"|trans }}">
                    {{ form_widget(form.taxes) }}
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "title.recipe.start_recipe %recipe%"|trans({'%recipe%':recipe.label}) }}</h3>
                </div>
                <div class="card-body p-3">
                    {% if fabrication.id is not null %}
                        <button data-toggle="tooltip" type="submit" class="submit btn btn-primary btn-block" value="start"><i
                                    class="fas fa-play"></i> {{ "button.recipe_fabrication.continue"|trans }}</button>
                        <button data-toggle="tooltip" type="submit" class="submit btn btn-danger btn-block"
                                value="stop"
                                data-title="{{ "title.recipe_fabrication.real_time"|trans }}"
                                data-hours="{{ fabrication.hours == 0 ? recipe.estimatedHours : fabrication.calculatedHours }}"
                        ><i class="fas fa-stop"></i> {{ "button.recipe_fabrication.stop"|trans }}</button>
                    {% else %}
                        <button data-toggle="tooltip" type="submit" class="submit btn-estimate btn btn-default btn-block" name="estimate" value="estimate"
                                data-title="{{ "title.recipe_fabrication.real_time"|trans }}"
                                data-hours="{{ fabrication.hours == 0 ? recipe.estimatedHours : fabrication.calculatedHours }}"
                        ><i
                                    class="fas fa-search-dollar"></i> {{ "button.recipe_fabrication.estimate"|trans }}</button>
                        <button data-toggle="tooltip" type="submit" class="submit btn btn-primary btn-block" value="start"><i
                                    class="fas fa-play"></i> {{ "button.recipe_fabrication.start"|trans }}</button>
                        <button data-toggle="tooltip" type="submit" class="submit btn btn-danger btn-block"
                                value="stop"
                                data-title="{{ "title.recipe_fabrication.real_time"|trans }}"
                                data-hours="{{ fabrication.hours == 0 ? recipe.estimatedHours : fabrication.calculatedHours }}"
                        ><i
                                    class="fas fa-stop"></i> {{ "button.recipe_fabrication.stop"|trans }}</button>
                        <button data-toggle="tooltip" class="btn btn-info btn-block disabled" name="programmer"><i
                                    class="fas fa-clock-o"></i> {{ "button.recipe_fabrication.programmer"|trans }}
                        </button>
                    {% endif %}

                </div>
            </div>
        </div>

    </div>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('form_recipe_fabrication') }}
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('form_recipe_fabrication') }}
{% endblock %}

templates/front/recipe_fabrication/start_recipe.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.recipe.start_recipe"|trans }} {{ parent() }}{% endblock %}

{% block contentHeader %}
    {% include 'tools/content_header.html.twig' with {title: "title.recipe.start_recipe"|trans } %}

{% endblock %}
{% block content %}
    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "title.recipe.start_recipe %recipe%"|trans({'%recipe%':recipe.label}) }}</h3>
                </div>
                <div class="card-body p-3">
                    <div data-intro="{{ "intro.text.recipe.marge"|trans }}">
                        {{ form_row(form.quantity) }}
                    </div>
                    <div data-intro="{{ "intro.text.recipe.marge"|trans }}">
                        {{ form_row(form.marge) }}
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "entity.recipe.label.recipeComponents"|trans }}</h3>
                </div>
                <div class="card-body p-0" data-intro="{{ "intro.text.recipe.components"|trans }}">
                    <table id="components-fields-list" class="table table-condensed">

                        <thead>
                        <tr>
                            <th>{{ "entity.recipe_component.label.component"|trans }}</th>
                            <th>{{ "entity.recipe_component.label.option"|trans }}</th>
                            <th>{{ "entity.recipe_component.label.quantity"|trans }}</th>
                            <th>{{ "entity.recipe_component.label.unit"|trans }}</th>
                            <th>{{ "entity.recipe_component.label.cost"|trans }}</th>
                        </tr>
                        </thead>
                        {% if fabrication.id is null %}
                            {% for component in recipe.recipeComponents %}
                                <tr>
                                    <td>{{ component.component.label }}</td>
                                    <td data-type="new" data-component="{{ component.id }}"></td>
                                    <td>{{ component.quantity }}</td>
                                    <td>{{ component.unit.libelle }}</td>
                                    <td class="price"></td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            {% for component in fabrication.recipeFabricationComponents %}
                                <tr>
                                    <td>{{ component.component.label }}</td>
                                    <td data-type="edit" data-component="{{ component.id }}"></td>
                                    <td>{{ component.quantity }}</td>
                                    <td>{{ component.unit.libelle }}</td>
                                    <td class="price"></td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "entity.recipe.label.taxes"|trans }}</h3>
                </div>
                <div class="card-body p-3" data-intro="{{ "intro.text.recipe.taxes"|trans }}">
                    {{ form_widget(form.taxes) }}
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "title.recipe.start_recipe %recipe%"|trans({'%recipe%':recipe.label}) }}</h3>
                </div>
                <div class="card-body p-3">
                    {% if fabrication.id is not null %}
                        <button type="submit" class="submit btn btn-primary btn-block" value="start"><i
                                    class="fas fa-play"></i> {{ "button.recipe_fabrication.continue"|trans }}</button>
                        <button type="submit" class="submit btn btn-danger btn-block"
                                value="stop"
                                data-title="{{ "title.recipe_fabrication.real_time"|trans }}"
                                data-hours="{{ fabrication.hours == 0 ? recipe.estimatedHours : fabrication.calculatedHours }}"
                        ><i class="fas fa-stop"></i> {{ "button.recipe_fabrication.stop"|trans }}</button>
                    {% else %}
                        <button type="submit" class="submit btn btn-primary btn-block" value="start"><i
                                    class="fas fa-play"></i> {{ "button.recipe_fabrication.start"|trans }}</button>
                        <button type="submit" class="submit btn btn-danger btn-block"
                                value="stop"
                                data-title="{{ "title.recipe_fabrication.real_time"|trans }}"
                                data-hours="{{ fabrication.hours == 0 ? recipe.estimatedHours : fabrication.calculatedHours }}"
                        ><i
                                    class="fas fa-stop"></i> {{ "button.recipe_fabrication.stop"|trans }}</button>
                        <button class="btn btn-info btn-block disabled" name="programmer"><i
                                    class="fas fa-clock-o"></i> {{ "button.recipe_fabrication.programmer"|trans }}
                        </button>
                    {% endif %}

                </div>
            </div>
        </div>

    </div>
    {{ form_end(form) }}

{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('form_recipe_fabrication') }}
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('form_recipe_fabrication') }}
{% endblock %}