src/Entity/Taxe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaxeRepository")
 */
class Taxe
{
    public const TYPE_PERCENTAGE = 10;
    public const TYPE_AMOUNT = 20;

    public const Types = [
        "entity.taxe.label.type_percentage" => self::TYPE_PERCENTAGE,
        "entity.taxe.label.type_amount" => self::TYPE_AMOUNT,
    ];

    const ReverseTypes = [
        self::TYPE_AMOUNT => "entity.taxe.label.type_amount",
        self::TYPE_PERCENTAGE => "entity.taxe.label.type_percentage",
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="taxes")
     */
    private $user;

    /**
     * @ORM\Column(type="decimal", precision=50, scale=5)
     */
    private $value;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Recipe", mappedBy="taxes")
     */
    private $recipes;

    /**
     * @ORM\Column(type="integer")
     */
    private $Type;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDefault;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isEnabledForCommunity = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enabled = true;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Taxe", inversedBy="children")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Taxe", mappedBy="parent")
     */
    private $children;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\RecipeFabrication", mappedBy="taxes")
     */
    private $recipeFabrications;

    public function __construct()
    {
        $this->recipes = new ArrayCollection();
        $this->children = new ArrayCollection();
        $this->recipeFabrications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getUser(): ?UserInterface
    {
        return $this->user;
    }

    public function setUser(?UserInterface $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Recipe[]
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipe $recipe): self
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes[] = $recipe;
            $recipe->addTax($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): self
    {
        if ($this->recipes->contains($recipe)) {
            $this->recipes->removeElement($recipe);
            $recipe->removeTax($this);
        }

        return $this;
    }

    public function getTypeStr(): ?string
    {
        return self::ReverseTypes[$this->getType()];
    }

    public function getType(): ?int
    {
        return $this->Type;
    }

    public function setType(int $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getIsDefault(): ?bool
    {
        return $this->isDefault;
    }

    public function setIsDefault(bool $isDefault): self
    {
        $this->isDefault = $isDefault;

        return $this;
    }

    public function getIsEnabledForCommunity(): ?bool
    {
        return $this->isEnabledForCommunity;
    }

    public function setIsEnabledForCommunity(bool $isEnabledForCommunity): self
    {
        $this->isEnabledForCommunity = $isEnabledForCommunity;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(self $child): self
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(self $child): self
    {
        if ($this->children->contains($child)) {
            $this->children->removeElement($child);
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|RecipeFabrication[]
     */
    public function getRecipeFabrications(): Collection
    {
        return $this->recipeFabrications;
    }

    public function addRecipeFabrication(RecipeFabrication $recipeFabrication): self
    {
        if (!$this->recipeFabrications->contains($recipeFabrication)) {
            $this->recipeFabrications[] = $recipeFabrication;
            $recipeFabrication->addTax($this);
        }

        return $this;
    }

    public function removeRecipeFabrication(RecipeFabrication $recipeFabrication): self
    {
        if ($this->recipeFabrications->contains($recipeFabrication)) {
            $this->recipeFabrications->removeElement($recipeFabrication);
            $recipeFabrication->removeTax($this);
        }

        return $this;
    }

}

src/Form/TaxeType.php
<?php

namespace App\Form;

use App\Entity\Taxe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaxeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle', TextType::class, [
                'label' => 'entity.taxe.label.libelle',
                'required' => true,
            ])
            ->add('description', TextareaType::class, [
                'label' => 'entity.taxe.label.description',
                'required' => false,

            ])
            ->add('value', NumberType::class, [
                'scale' => 5,
                'label' => 'entity.taxe.label.value',
                'required' => true,
            ])
            ->add('isDefault', CheckboxType::class, [
                'required' => false,
                'label' => 'entity.taxe.label.isDefault',
            ])
            ->add('type', ChoiceType::class, [
                'choices' => Taxe::Types,
                'required' => true,
                'label' => 'entity.taxe.label.type',
            ])->add('enabled', CheckboxType::class, [
                'required' => false,
                'label' => 'entity.taxe.label.enabled',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Taxe::class,
        ]);
    }
}

src/Controller/TaxeController.php
<?php

namespace App\Controller;

use App\Entity\Taxe;
use App\Form\TaxeType;
use App\Repository\TaxeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/taxe")
 */
class TaxeController extends AbstractController
{
    /**
     * @Route("/", name="taxe_index", methods={"GET"})
     */
    public function index(TaxeRepository $taxeRepository): Response
    {
        $myTaxes = $taxeRepository->findBy(['user' => $this->getUser()]);

        $qb = $taxeRepository->createQueryBuilder('t')
            ->leftJoin('t.children', 'child')
            ->where('t.isEnabledForCommunity = true')
            ->andWhere('t.enabled = true')
            ->andWhere('(  child.user != :user  OR child.id IS NULL)')
            ->setParameter('user', $this->getUser());

        return $this->render('front/taxe/index.html.twig', [
            'taxes' => $myTaxes,
            'community_taxes' => $qb->orderBy('t.libelle')->getQUery()->getResult(),
        ]);


    }

    /**
     * @Route("/new", name="taxe_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $taxe = new Taxe();
        $form = $this->createForm(TaxeType::class, $taxe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $taxe->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($taxe);
            $entityManager->flush();

            return $this->redirectToRoute('taxe_index');
        }

        return $this->render('front/taxe/new.html.twig', [
            'taxe' => $taxe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="taxe_show", methods={"GET"})
     */
    public function show(Taxe $taxe): Response
    {
        return $this->render('front/taxe/show.html.twig', [
            'taxe' => $taxe,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="taxe_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Taxe $taxe): Response
    {
        if ($this->getUser() != $taxe->getUser()) {
            $this->addFlash('danger', 'text.danger.not_yours');
            return $this->redirectToRoute('taxe_index');
        }
        $form = $this->createForm(TaxeType::class, $taxe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('taxe_index');
        }

        return $this->render('front/taxe/edit.html.twig', [
            'taxe' => $taxe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/copy", name="taxe_copy_to_mine", methods={"GET"})
     * @param Taxe $taxe
     * @param TaxeRepository $taxeRepository
     * @return Response
     */
    public function copy(Taxe $taxe, TaxeRepository $taxeRepository): Response
    {
        if (!$taxe->getIsEnabledForCommunity()) {
            $this->addFlash('danger', 'text.danger.not_community_elt');
            return $this->redirectToRoute('taxe_index');
        }
        if ($taxeRepository->findOneby(['user' => $this->getUser(), 'parent' => $taxe])) {
            $this->addFlash('danger', 'text.danger.already_copied');
            return $this->redirectToRoute('taxe_index');
        }
        $em = $this->getDoctrine()->getManager();
        $taxeCopied = new Taxe();
        $taxeCopied->setUser($this->getUser());
        $taxeCopied->setLibelle($taxe->getLibelle());
        $taxeCopied->setParent($taxe);
        $taxeCopied->setDescription($taxe->getDescription());
        $taxeCopied->setType($taxe->getType());
        $taxeCopied->setValue($taxe->getValue());
        $taxeCopied->setEnabled(true);
        $taxeCopied->setIsDefault(false);
        $taxeCopied->setIsEnabledForCommunity(false);
        $em->persist($taxeCopied);
        $em->flush();
        $this->addFlash("success", 'text.success.copied_elt');

        return $this->redirectToRoute('taxe_index');

    }

    /**
     * @Route("/{id}", name="taxe_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Taxe $taxe): Response
    {
        if ($this->getUser() != $taxe->getUser()) {
            $this->addFlash('danger', 'text.danger.not_yours');
            return $this->redirectToRoute('taxe_index');
        }
        if ($this->isCsrfTokenValid('delete' . $taxe->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($taxe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('taxe_index');
    }
}

templates/front/taxe/_delete_form.html.twig
<form method="post" action="{{ path('taxe_delete', {'id': taxe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ taxe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/front/taxe/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ title }}</h3>
            </div>
            <div class="card-body p-3">
                {{ form_row(form.libelle) }}
                {{ form_row(form.description) }}
                <div class="row">
                    <div class="col-6">{{ form_row(form.value) }}</div>
                    <div class="col-6">{{ form_row(form.type) }}</div>
                </div>
                <div class="row">
                    <div class="col-6">{{ form_row(form.isDefault) }}</div>
                    <div class="col-6">{{ form_row(form.enabled) }}</div>
                </div>
                <button class="btn btn-primary btn-sm">{{ button_label|default('button.default.add'|trans) }}</button>
            </div>
        </div>
    </div>
</div>

{{ form_end(form) }}

templates/front/taxe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.taxe.edit"|trans }} {{ parent() }}{% endblock %}

{% block contentHeader %}
{% include "tools/content_header.html.twig" with {title : "title.taxe.edit"|trans} %}
{% endblock %}
{% block content %}

    {{ include('front/taxe/_form.html.twig', {'button_label': 'button.default.edit'|trans, title: "title.taxe.edit"|trans}) }}

{% endblock %}

templates/front/taxe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'title.taxe.index'|trans }} {{ parent() }}{% endblock %}

{% block contentHeader %}
    {% include 'tools/content_header.html.twig' with {title: 'title.taxe.index'|trans} %}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "title.taxe.index"|trans }}</h3>
                    <a data-intro="{{ "intro.text.taxe.add_taxes"|trans }}" class='btn btn-sm btn-success float-right' href="{{ path('taxe_new') }}"><i
                                class="fas fa-plus "></i> {{ "button.default.add"|trans }}</a>
                </div>
                <div class="card-body p-0">
                    <table class="table table-condensed" data-intro="{{ "intro.text.taxe.your_taxes"|trans }}">
                        <thead>
                        <tr>
                            <th>{{ "entity.taxe.label.libelle"|trans }}</th>
                            <th>{{ "entity.taxe.label.description"|trans }}</th>
                            <th>{{ "entity.taxe.label.value"|trans }}</th>
                            <th>{{ "entity.taxe.label.type"|trans }}</th>
                            <th>{{ "text.action"|trans }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for taxe in taxes %}
                            <tr>
                                <td>{{ taxe.libelle }}</td>
                                <td>{{ taxe.description }}</td>
                                <td>{{ taxe.value }}</td>
                                <td>{{ taxe.typeStr|trans }}</td>
                                <td>
                                    <a href="{{ path('taxe_edit', {'id': taxe.id}) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="6">{{ "text.no_taxe"|trans }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ "title.taxe.index_community"|trans }}</h3>
                </div>
                <div class="card-body p-0">
                    <table class="table table-condensed"  data-intro="{{ "intro.text.taxe.community_taxes"|trans }}">
                        <thead>
                        <tr>
                            <th>{{ "entity.taxe.label.libelle"|trans }}</th>
                            <th>{{ "entity.taxe.label.description"|trans }}</th>
                            <th>{{ "entity.taxe.label.value"|trans }}</th>
                            <th>{{ "entity.taxe.label.type"|trans }}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for taxe in community_taxes %}
                            <tr>
                                <td>{{ taxe.libelle }}</td>
                                <td>{{ taxe.description }}</td>
                                <td>{{ taxe.value }}</td>
                                <td>{{ taxe.typeStr|trans }}</td>
                                <td>
                                    <a href="{{ url('taxe_copy_to_mine',{id:taxe.id}) }}" class="btn btn-sm btn-success" data-toggle="tooltip" title="Ajouter à mes taxes">
                                        <i class="fas fa-plus"></i>
                                    </a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="6">{{ "text.no_taxe"|trans }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/front/taxe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.taxe.new"|trans }} {{ parent() }}{% endblock %}

{% block contentHeader %}
    {% include "tools/content_header.html.twig" with {title : "title.taxe.new"|trans} %}
{% endblock %}
{% block content %}

    {{ include('front/taxe/_form.html.twig',{title:"title.taxe.new"|trans}) }}

{% endblock %}

templates/front/taxe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Taxe{% endblock %}

{% block body %}
    <h1>Taxe</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ taxe.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ taxe.libelle }}</td>
            </tr>
            <tr>
                <th>Priority</th>
                <td>{{ taxe.priority }}</td>
            </tr>
            <tr>
                <th>Value</th>
                <td>{{ taxe.value }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ taxe.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('taxe_index') }}">back to list</a>

    <a href="{{ path('taxe_edit', {'id': taxe.id}) }}">edit</a>

    {{ include('taxe/_delete_form.html.twig') }}
{% endblock %}